### PR TITLE
Early example .ttl files written

### PR DESCRIPTION
**Pull request by add33m**
Are we considering this good enough for an initial RDF schema or should we expand further?

Also, I'm not sure if proper syntax has been exercised. Not super familiar with RDF/turtle.

### CODE REVIEW

**Comment by antonnyst** [comment]
Good start, and the syntax looks good. 

I do think we want to define some classes to go with the properties such as product and sawblade. (rdfs:Class)
As well as some relations between the properties and classes. 
(rdfs:range och rdfs:domain)

I found section 5 of https://www.w3.org/2007/02/turtle/primer/ to explain classes and properties pretty well

**Comment by Kebertr** [comment]
An example of your code with classes and properties:
product:
@prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#> .

@base <http://ceb.ltu.se/broker/> .

:product a rdfs:Class .

:product:name a rdf:Property;
    rdfs:domain :product;
    rdfs:label "Product Name" ;
	rdfs:comment "The name of the product." .


:product:id a rdf:Property;
    rdfs:domain :product;
	rdfs:label "Product Number" ;
	rdfs:comment "The identifying number/id of the product." .

product:manufacturer a rdf:Property ;
    rdfs:domain :product;
	rdfs:label "Product Manufacturer" ;
	rdfs:comment "The company manufacturing the product" .


sawblade:
@prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>^^xsd:anyURI .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#>^^xsd:anyURI .

@prefix sawblade: <http://ceb.ltu.se/components/sawblade>^^xsd:anyURI .
@prefix product: <http://ceb.ltu.se/broker/product>^^xsd:anyURI .

:sawblade a rdfs:Class;
     rdfs:subClassOf :product.

sawblade:teethGrade a rdfs:Property ;
    rdfs:domain :sawblade;
	rdfs:isDefinedBy <http://ceb.ltu.se/components/sawblade> ;
	rdfs:label "Teeth Grade" ;
	rdfs:comment "The fineness/grade of the teeth." .

sawblade:teethAmount a rdfs:Property ;
    rdfs:domain :sawblade;
	rdfs:isDefinedBy <http://ceb.ltu.se/components/sawblade> ;
	rdfs:label "Teeth Amount" ;
	rdfs:comment "The amount of teeth on the sawblade." .

**Comment by add33m** [comment]
Updated based on Kebert's suggestion

**Review by K4ffeMan — APPROVED** [review]
lgtm

**Review by antonnyst — APPROVED** [review]

**Pull request merged**
